name: "Deploy"
on:
    push:
        tags:
            - '*.*.*'

jobs:
    deployment:
        runs-on: ubuntu-latest
        container: ghcr.io/sitkoru/actions-container
        steps:
            -   uses: actions/checkout@v2
            -   name: Setup dotnet 5.0
                uses: actions/setup-dotnet@v1
                with:
                    dotnet-version: '5.0.100-rc.1.20452.10'
            -   name: Prepare
                id: prep
                shell: bash
                run: |
                    DOCKER_IMAGE=${{ secrets.DOCKER_REGISTRY_URL }}/${{ secrets.DOCKER_IMAGE_NAME }}
                    VERSION=${GITHUB_REF#refs/tags/}
                    TAGS="${DOCKER_IMAGE}:${VERSION}"
                    if [[ $VERSION =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
                        MINOR=${VERSION%.*}
                        MAJOR=${MINOR%.*}
                        TAGS="$TAGS,${DOCKER_IMAGE}:${MINOR},${DOCKER_IMAGE}:${MAJOR},${DOCKER_IMAGE}:latest"
                    fi
                    echo ::set-output name=tags::${TAGS}
                    echo ::set-output name=version::${VERSION}
                    echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
