name: Build

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: self-hosted
        container: ghcr.io/sitkoru/actions-container
        steps:
            -   name: Setup dotnet 5.0
                uses: actions/setup-dotnet@v1
                with:
                    dotnet-version: '5.0.100-rc.1.20452.10'
            -   name: Build
                run: dotnet publish --output /app/ --configuration Release
